---
# tasks file for javarole
- name: i want to install java 8 on ubuntu
  apt: 
         name: "{{javapackforubuntu}}"
         state: present 
  When : ansible_os_family=="Debian"

- name: i want to install java 8 on Redhat
  yum:
          name: "{{javapackforredhat}}"
          state: present
  When : ansible_os_family=="RedHat"